server {
    listen 80;
    server_name skyhoy.jonh.no;
    root /www/skyhoy;
    index index.html;
    location /.well-known/acme-challenge/ { root /var/www/certbot; }
    location / { try_files $uri $uri/ =404; }
    add_header Cache-Control "no-cache";
    add_header X-Content-Type-Options nosniff always;
}
